# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='chainctr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rrequest.proto\x12\x08\x63hainctr\"\xcc\x02\n\x04Info\x12\x11\n\tips_fixed\x18\x01 \x03(\t\x12\x12\n\nvalidators\x18\x02 \x03(\t\x12+\n\tvalidator\x18\x03 \x01(\x0b\x32\x18.chainctr.Info.Validator\x12#\n\x03rpc\x18\x04 \x01(\x0b\x32\x16.chainctr.Info.service\x12$\n\x04peer\x18\x05 \x01(\x0b\x32\x16.chainctr.Info.service\x12\"\n\x02ws\x18\x06 \x01(\x0b\x32\x16.chainctr.Info.service\x12\x0c\n\x04host\x18\x07 \x01(\t\x1a\x44\n\x07service\x12\x0c\n\x04port\x18\x01 \x02(\x05\x12\n\n\x02ip\x18\x02 \x02(\t\x12\r\n\x05\x61\x64min\x18\x03 \x02(\t\x12\x10\n\x08protocol\x18\x04 \x01(\t\x1a-\n\tValidator\x12\x12\n\npublic_key\x18\x01 \x02(\t\x12\x0c\n\x04seed\x18\x02 \x01(\t\"\xa2\x01\n\x07Request\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.chainctr.Request.Type\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x1c\n\x04info\x18\x03 \x01(\x0b\x32\x0e.chainctr.Info\"G\n\x04Type\x12\x08\n\x04join\x10\x00\x12\t\n\x05start\x10\x01\x12\x0b\n\x07restart\x10\x02\x12\x08\n\x04stop\x10\x03\x12\t\n\x05watch\x10\x04\x12\x08\n\x04list\x10\x05\"\xa3\x01\n\x08Response\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\nerror_code\x18\x02 \x02(\x05\x12)\n\x06result\x18\x03 \x01(\x0b\x32\x19.chainctr.Response.Result\x1aL\n\x06Result\x12\r\n\x05\x65rror\x18\x01 \x02(\x05\x12\x15\n\rerror_message\x18\x02 \x02(\t\x12\x1c\n\x04info\x18\x03 \x01(\x0b\x32\x0e.chainctr.Info')
)



_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chainctr.Request.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='join', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='start', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='restart', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='stop', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='watch', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='list', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=454,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_TYPE)


_INFO_SERVICE = _descriptor.Descriptor(
  name='service',
  full_name='chainctr.Info.service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='chainctr.Info.service.port', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='chainctr.Info.service.ip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin', full_name='chainctr.Info.service.admin', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='chainctr.Info.service.protocol', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=313,
)

_INFO_VALIDATOR = _descriptor.Descriptor(
  name='Validator',
  full_name='chainctr.Info.Validator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='chainctr.Info.Validator.public_key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='chainctr.Info.Validator.seed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=360,
)

_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='chainctr.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ips_fixed', full_name='chainctr.Info.ips_fixed', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validators', full_name='chainctr.Info.validators', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validator', full_name='chainctr.Info.validator', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpc', full_name='chainctr.Info.rpc', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer', full_name='chainctr.Info.peer', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ws', full_name='chainctr.Info.ws', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='chainctr.Info.host', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFO_SERVICE, _INFO_VALIDATOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=360,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='chainctr.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chainctr.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='chainctr.Request.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='chainctr.Request.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=525,
)


_RESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='chainctr.Response.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='chainctr.Response.Result.error', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='chainctr.Response.Result.error_message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='chainctr.Response.Result.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=691,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='chainctr.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chainctr.Response.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='chainctr.Response.error_code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='chainctr.Response.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=691,
)

_INFO_SERVICE.containing_type = _INFO
_INFO_VALIDATOR.containing_type = _INFO
_INFO.fields_by_name['validator'].message_type = _INFO_VALIDATOR
_INFO.fields_by_name['rpc'].message_type = _INFO_SERVICE
_INFO.fields_by_name['peer'].message_type = _INFO_SERVICE
_INFO.fields_by_name['ws'].message_type = _INFO_SERVICE
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_TYPE
_REQUEST.fields_by_name['info'].message_type = _INFO
_REQUEST_TYPE.containing_type = _REQUEST
_RESPONSE_RESULT.fields_by_name['info'].message_type = _INFO
_RESPONSE_RESULT.containing_type = _RESPONSE
_RESPONSE.fields_by_name['result'].message_type = _RESPONSE_RESULT
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(

  service = _reflection.GeneratedProtocolMessageType('service', (_message.Message,), dict(
    DESCRIPTOR = _INFO_SERVICE,
    __module__ = 'request_pb2'
    # @@protoc_insertion_point(class_scope:chainctr.Info.service)
    ))
  ,

  Validator = _reflection.GeneratedProtocolMessageType('Validator', (_message.Message,), dict(
    DESCRIPTOR = _INFO_VALIDATOR,
    __module__ = 'request_pb2'
    # @@protoc_insertion_point(class_scope:chainctr.Info.Validator)
    ))
  ,
  DESCRIPTOR = _INFO,
  __module__ = 'request_pb2'
  # @@protoc_insertion_point(class_scope:chainctr.Info)
  ))
_sym_db.RegisterMessage(Info)
_sym_db.RegisterMessage(Info.service)
_sym_db.RegisterMessage(Info.Validator)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'request_pb2'
  # @@protoc_insertion_point(class_scope:chainctr.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_RESULT,
    __module__ = 'request_pb2'
    # @@protoc_insertion_point(class_scope:chainctr.Response.Result)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'request_pb2'
  # @@protoc_insertion_point(class_scope:chainctr.Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Result)


# @@protoc_insertion_point(module_scope)
